### ISSUE TITLE
Most `slides →` links on /talks now lead to 404

### ISSUE THREAD

**Issue by choznerol** [rmosolgo/rmosolgo.github.io#3]
Assets like [/assets/getting_down_to_business_with_graphql.pdf](https://github.com/rmosolgo/rmosolgo.github.io/blob/master/talks.html#L13) is missing on the [current HEAD](https://github.com/rmosolgo/rmosolgo.github.io/tree/a3365d1b707e9fdd967cf698b518882a385b0ec4/assets), therefore most `slides →` links on https://rmosolgo.github.io/talks lead to a 404 page.

> <img width="1042" alt="圖片" src="https://user-images.githubusercontent.com/12410942/106344703-6582c080-62e6-11eb-9416-8b4931dc4903.png">
> <img width="1107" alt="圖片" src="https://user-images.githubusercontent.com/12410942/106344774-c6aa9400-62e6-11eb-9093-f188c9c0bf55.png">

**Comment by rmosolgo** [comment]
Thanks for letting me know! I just added those assets to the project and updated the links on that page. I guess I missed them in the migration from octopress 😅
